#!/usr/bin/env ruby

$:.unshift File.dirname(__FILE__) + "/../lib"

require 'rubygems'
require 'bundler/setup'
require 'mundane-search'

require './spec/active_record_setup'

def minitest!
  require './spec/minitest_helper'
end

begin
  require 'pry'
  Pry.start
rescue LoadError
  require 'irb'
  IRB.start
end
